name: Integration Test
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            argocd/data/token admin | ARGOCD_TOKEN ;

      - name: Self test
        id: selftest
        uses: safe2008/argocd-app-actions@master
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          token: ${{ steps.secrets.outputs.ARGOCD_TOKEN }}
          appName: horusec-platform

